name: regreen
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  image_picker: ^1.2.1
  youtube_player_flutter: 9.1.3
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - Assets/
    - Assets/onboarding/
    - Assets/profile.jpg
    - Assets/schedule/

flutter_native_splash:
  color: "#EFF3E5"

  image: Assets/Logo-Regreen-with-text.png

  android_12:
    image: Assets/Logo-Regreen-with-text.png
    icon_background_color: "#EFF3E5"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Assets/Logo-ReGreen-Without-Text.png"
  min_sdk_android: 21

  adaptive_icon_background: "#EFF3E5"
  adaptive_icon_foreground: "Assets/Logo-ReGreen-Without-Text.png"